# Generated by Django 5.0.6 on 2024-09-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cargo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoría')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('dni_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='DNI Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Marca')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pais')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Provincia')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Stock')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni_empleado', models.AutoField(primary_key=True, serialize=False, verbose_name='DNI Empleado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_admision', models.DateField(verbose_name='Fecha de Admisión')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.cargos', verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Compra')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empleados', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Presupuesto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.clientes', verbose_name='Clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empleados', verbose_name='Empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tamaño')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.categorias', verbose_name='Categorías')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.marcas', verbose_name='Marcas')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.stock', verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id_detalle_presupuesto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Presupuesto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.presupuestos', verbose_name='Presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.productos', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('dni_proveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='DNI Proveedor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.paises', verbose_name='País')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.provincias', verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Compra')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.compras', verbose_name='Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.productos', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.proveedores', verbose_name='Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.proveedores', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Almacén')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tamaño')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.provincias', verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Remitos',
            fields=[
                ('id_remito', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Remito')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp_CODEMC.almacenes', verbose_name='Almacén')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.clientes', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empleados', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesRemitos',
            fields=[
                ('id_detalle_remito', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Remito')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.productos', verbose_name='Almacén')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.remitos', verbose_name='Remito')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategorias',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Subcategoría')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.categorias', verbose_name='Categoría')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.subcategorias', verbose_name='Subcategorías'),
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sucursal')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.almacenes', verbose_name='Almacén')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.provincias', verbose_name='Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='remitos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp_CODEMC.sucursales', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.sucursales', verbose_name='Sucursales'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('alias', models.CharField(max_length=100, verbose_name='Alias')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empleados', verbose_name='Empleado')),
            ],
        ),
    ]
