# Generated by Django 5.0.6 on 2024-11-12 20:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=50, unique=True, verbose_name='CUIT')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Razón social')),
                ('telefono', models.CharField(max_length=50, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email de contacto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción de actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Stock')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=120, null=True, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=120, verbose_name='Teléfono')),
                ('rol', models.CharField(default='manager', max_length=10, null=True, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='miapp_CODEMC.empresa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Compra')),
                ('orden', models.CharField(max_length=30, null=True, verbose_name='Número de compra')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('iva', models.DecimalField(choices=[(21, 'General (21%)'), (10.5, 'Reducido (10.5%)'), (27, 'Aumentado (27%)')], decimal_places=1, default=21.0, max_digits=4, verbose_name='IVA (%)')),
                ('forma_pago', models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50, null=True, verbose_name='Método de pago')),
                ('usuario_a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a cargo')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='miapp_CODEMC.businessmanager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_cliente', models.CharField(max_length=120, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoría')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False, verbose_name='id_almacen')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tamaño')),
                ('unidad_medida', models.CharField(choices=[('Metros cuadrados', 'm²'), ('Decámetros cuadrados', 'dam²'), ('Hectómetros cuadrados', 'hm²')], default='Metros cuadrados', max_length=30, verbose_name='Unidad de medida')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Presupuesto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.cliente', verbose_name='Clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empleado', verbose_name='Empleados')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto', models.CharField(max_length=100, verbose_name='Código de producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tamaño')),
                ('unidad_medida', models.CharField(blank=True, choices=[('Litros', 'L'), ('Milílitros', 'ml'), ('Centímetros cúbicos', 'cm³ - cc'), ('Kilogramos', 'kg'), ('Gramos', 'g'), ('Centímetros cúbicos', 'cm³ - cc'), ('Talla XS', 'Talla XS'), ('Talla S', 'Talla S'), ('Talla M', 'Talla M'), ('Talla L', 'Talla L'), ('Talla XL', 'Talla XL')], max_length=30, null=True, verbose_name='Unidad de medida')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Descuento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.categoria', verbose_name='Categorías')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.stock', verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id_detalle_presupuesto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Presupuesto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.presupuesto', verbose_name='Presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.producto', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Compra')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (porcentaje)')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp_CODEMC.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.producto', verbose_name='producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=25, null=True, verbose_name='CUIT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Razón social/Nombre')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('pais', django_countries.fields.CountryField(max_length=2, verbose_name='País de residencia')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web (opcional)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Observaciones (opcional)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id_remito', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Remito')),
                ('orden', models.CharField(max_length=30, verbose_name='Número de remito')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('iva', models.DecimalField(choices=[(21, 'General (21%)'), (10.5, 'Reducido (10.5%)'), (27, 'Aumentado (27%)')], decimal_places=1, default=21.0, max_digits=4, verbose_name='IVA (%)')),
                ('forma_pago', models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50, null=True, verbose_name='Método de pago')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa')),
                ('usuario_a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a cargo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemito',
            fields=[
                ('id_detalle_remito', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Remito')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (porcentaje)')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp_CODEMC.producto', verbose_name='Producto')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.remito', verbose_name='Remito')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Subcategoría')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.subcategoria', verbose_name='Subcategorías'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sucursal')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro_calle', models.IntegerField(verbose_name='Número de Calle')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.almacen', verbose_name='Almacén')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='miapp_CODEMC.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.sucursal', verbose_name='Sucursales'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.almacen')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='remito',
            name='ubicacion',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.ubicacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.ubicacion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='ubicacion',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.ubicacion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ubicacion',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.ubicacion'),
        ),
    ]
