# Generated by Django 5.0.6 on 2024-11-10 21:54
from django.db import migrations

def triggers(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
                    CREATE TRIGGER update_stock_after_detalleremito_insert
                    AFTER INSERT ON miapp_codemc_detalleremito        
                    FOR EACH ROW     
                    BEGIN
                    UPDATE miapp_codemc_stock
                    SET cantidad = cantidad - NEW.cantidad
                    WHERE id_stock = (SELECT stock_id FROM miapp_codemc_producto WHERE id = NEW.producto_id);

                    END; 
                """)

class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(triggers)
    ]
