# Generated by Django 5.0.6 on 2024-11-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Litros', 'L'), ('Milílitros', 'ml'), ('Centímetros cúbicos', 'cm³ - cc'), ('Kilogramos', 'kg'), ('Gramos', 'g'), ('Centímetros cúbicos', 'cm³ - cc'), ('Talla XS', 'Talla XS'), ('Talla S', 'Talla S'), ('Talla M', 'Talla M'), ('Talla L', 'Talla L'), ('Talla XL', 'Talla XL')], max_length=30, null=True, verbose_name='Unidad de medida'),
        ),
    ]
