# Generated by Django 5.0.6 on 2024-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='id_almacen',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id_almacen'),
        ),
    ]
