# Generated by Django 5.0.6 on 2024-11-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa'),
        ),
        migrations.AddField(
            model_name='remito',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa'),
        ),
    ]
