# Generated by Django 5.0.6 on 2024-10-26 19:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='provincia',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='AR', verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='unidad_medida',
            field=models.CharField(choices=[('metro_cuadrado', 'm²'), ('decametro_cuadrado', 'dam²'), ('hectometro_cuadrado', 'hm²')], default='metro_cuadrado', max_length=30, verbose_name='Unidad de medida'),
        ),
    ]
