# Generated by Django 5.0.6 on 2024-10-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cuit', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Cuit Empresa')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=50, verbose_name='CUIT/Razón social')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='almacenes',
            name='id_almacen',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Almacén'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dni_cliente',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='DNI Cliente'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp_CODEMC.cargos', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni_empleado',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='DNI Empleado'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='dni_proveedor',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='DNI Proveedor'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='id_sucursal',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Sucursal'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('alias', models.CharField(max_length=100, verbose_name='Alias')),
                ('is_superuser', models.BooleanField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empleados', verbose_name='Empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
