# Generated by Django 5.0.6 on 2024-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(default='manager', max_length=10, null=True, verbose_name='Rol'),
        ),
    ]
