# Generated by Django 5.0.6 on 2024-10-18 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmanager',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefes', to='miapp_CODEMC.empresa'),
        ),
        migrations.AlterField(
            model_name='businessmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='miapp_CODEMC.businessmanager'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
    ]
