# Generated by Django 5.0.6 on 2024-11-11 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0002_crear_triggers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='empleado',
        ),
        migrations.AddField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(choices=[(21, 'General (21%)'), (10.5, 'Reducido (10.5%)'), (27, 'Aumentado (27%)')], decimal_places=1, default=21.0, max_digits=4, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario_a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a cargo'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (porcentaje)'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='forma_pago',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50, null=True, verbose_name='Método de pago'),
        ),
    ]
