# Generated by Django 5.0.6 on 2024-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0002_alter_almacen_id_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='provincia',
            field=models.CharField(max_length=100, verbose_name='Provincia'),
        ),
    ]
