# Generated by Django 5.0.6 on 2024-10-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0002_alter_almacen_provincia_alter_almacen_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='unidad_medida',
            field=models.CharField(choices=[('Metros cuadrados', 'm²'), ('Decámetros cuadrados', 'dam²'), ('Hectómetros cuadrados', 'hm²')], default='Metros cuadrados', max_length=30, verbose_name='Unidad de medida'),
        ),
    ]
