# Generated by Django 5.0.6 on 2024-11-06 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0002_compra_empresa_presupuesto_empresa_remito_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remito',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='remito',
            name='jefe',
        ),
        migrations.AddField(
            model_name='remito',
            name='usuario_a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a cargo'),
        ),
    ]
