# Generated by Django 5.0.6 on 2024-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0003_remove_compra_empleado_compra_forma_pago_compra_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='orden',
            field=models.CharField(max_length=30, null=True, verbose_name='Número de compra'),
        ),
    ]
