# Generated by Django 5.0.6 on 2024-10-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0003_alter_almacen_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmanager',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.empresa'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(max_length=10, null=True, verbose_name='Rol'),
        ),
    ]
