# Generated by Django 5.0.6 on 2024-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0004_businessmanager_ubicacion_empleado_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
