# Generated by Django 5.0.6 on 2024-11-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0004_compra_orden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp_CODEMC.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='detalleremito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp_CODEMC.producto', verbose_name='Producto'),
        ),
    ]
