# Generated by Django 5.0.6 on 2024-11-06 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0004_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.producto', verbose_name='Producto'),
        ),
    ]
