# Generated by Django 5.0.6 on 2024-11-07 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp_CODEMC', '0005_alter_detalleremito_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp_CODEMC.producto', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='detalleremito',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (porcentaje)'),
        ),
    ]
